hunav_loader:
  ros__parameters:
    map: intersection_hallway
    publish_people: true
    agents:
      - worker1
      - worker2
      - worker3
      - worker4
    worker1:
      id: 1
      skin: 0
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior: 
        type: 1 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -9.5
        y: -1.0
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: 9.5
        y: -1.0
        h: 1.250000
      g1:
        x: 9.5
        y: 1.0
        h: 1.250000
      g2:
        x: -9.5
        y: 1.0
        h: 1.250000
      g3:
        x: -9.5
        y: -1.0
        h: 1.250000
    worker2:
      id: 2
      skin: 0
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior: 
        type: 1 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 9.5
        y: 1.0
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: -9.5
        y: 1.0
        h: 1.250000
      g1:
        x: -9.5
        y: -1.0
        h: 1.250000
      g2:
        x: 9.5
        y: -1.0
        h: 1.250000
      g3:
        x: 9.5
        y: 1.0
        h: 1.250000
    worker3:
      id: 3
      skin: 0
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior: 
        type: 1 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -1.0
        y: 9.5
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: -1.0
        y: -9.5
        h: 1.250000
      g1:
        x: 1.0
        y: -9.5
        h: 1.250000
      g2:
        x: 1.0
        y: 9.5
        h: 1.250000
      g3:
        x: -1.0
        y: 9.5
        h: 1.250000
    worker4:
      id: 4
      skin: 0
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior: 
        type: 1 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 1.0
        y: -9.5
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: 1.0
        y: 9.5
        h: 1.250000
      g1:
        x: -1.0
        y: 9.5
        h: 1.250000
      g2:
        x: -1.0
        y: -9.5
        h: 1.250000
      g3:
        x: 1.0
        y: -9.5
        h: 1.250000